Dataset:
  dataset: sunrefer2d
  max_query_len: 50
  type: 2d

Backbone:
  backbone: resnet50
  dilation: False
  position_embedding: sine

Transformer:
  enc_layers: 6
  dec_layers: 0
  dim_feedforward: 2048
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  num_queries: 100
  pre_norm: False
  imsize: 640
  emb_size: 512

  bert_enc_num: 12
  detr_enc_num: 6

VisionLanguageTransformer:
  vl_dropout: 0.1
  vl_nheads: 8
  vl_hidden_dim: 256
  vl_dim_feedforward: 2048
  vl_enc_layers: 6
  out_dim: 4

PretainedModel:
  detr_model: ./saved_models/detr-r50.pth
  bert_model: bert-base-uncased

TrainingConfig:
  lr: 0.0001
  lr_bert: 0.00001
  lr_visu_cnn: 0.00001
  lr_visu_tra: 0.00001

  batch_size: 16
  weight_decay: 0.0001
  epochs: 90
  lr_power: 0.9
  clip_max_norm: 0.0
  eval: False
  optimizer: adamw
  lr_scheduler: step
  lr_drop: 60

  device: cuda
  seed: 13
